# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelPackages = pkgs.linuxPackages_latest; # Maybe fix issues with shutting down system?
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    loader = {
      grub = {
        enable = true;
        device = "nodev";
        efiSupport = true;
      };
      efi.canTouchEfiVariables = true;
    };
    initrd = {
      kernelModules = [ "i915" "dm_snapshot" ];
      availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
      luks = { 
        fido2Support = true;
        devices.cryptroot = {
          device = "/dev/disk/by-uuid/41ee166d-f7bd-42ea-88f7-1eb181d49f27";
          fido2.credential = "c696abc52e90b744640390f8efdb3f0e";
        };
      };
    };
    kernelParams = [ "i915.force_probe=7d55" ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9fa5f076-aebe-4251-af8f-968eaf41194c";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c01beff2-a947-488a-b946-feed52508c67";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4D3B-1C6A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics.enable = true;

  services.acpid.enable = true;
}
